/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.Monitoramento;

/**
 *
 * @author Victor
 */
public class MonitoracaoTabelaDeAlteracaoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MonitoraçãoTabelaDeAlteracaoJPanel
     */
    public MonitoracaoTabelaDeAlteracaoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MonitoracaoTabelaDeAlteracaoJPanel = new javax.swing.JPanel();
        MonitoracaoTabelaDeAlteracaoJScrollPane = new javax.swing.JScrollPane();
        MonitoracaoTabelaDeAlteracaoJTable = new javax.swing.JTable();

        MonitoracaoTabelaDeAlteracaoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela de Alterações", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        MonitoracaoTabelaDeAlteracaoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Alteração", "Data", "Ações"
            }
        ){
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        });
        MonitoracaoTabelaDeAlteracaoJScrollPane.setViewportView(MonitoracaoTabelaDeAlteracaoJTable);

        javax.swing.GroupLayout MonitoracaoTabelaDeAlteracaoJPanelLayout = new javax.swing.GroupLayout(MonitoracaoTabelaDeAlteracaoJPanel);
        MonitoracaoTabelaDeAlteracaoJPanel.setLayout(MonitoracaoTabelaDeAlteracaoJPanelLayout);
        MonitoracaoTabelaDeAlteracaoJPanelLayout.setHorizontalGroup(
            MonitoracaoTabelaDeAlteracaoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MonitoracaoTabelaDeAlteracaoJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        MonitoracaoTabelaDeAlteracaoJPanelLayout.setVerticalGroup(
            MonitoracaoTabelaDeAlteracaoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonitoracaoTabelaDeAlteracaoJPanelLayout.createSequentialGroup()
                .addComponent(MonitoracaoTabelaDeAlteracaoJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonitoracaoTabelaDeAlteracaoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonitoracaoTabelaDeAlteracaoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MonitoracaoTabelaDeAlteracaoJPanel;
    private javax.swing.JScrollPane MonitoracaoTabelaDeAlteracaoJScrollPane;
    private javax.swing.JTable MonitoracaoTabelaDeAlteracaoJTable;
    // End of variables declaration//GEN-END:variables
}
