/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import facade.PoliticaOrganizacionalFacade;
import facade.ProjetoPlanoRiscoFacade;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Politicaorganizacional;
import model.Projeto;

/**
 *
 * @author MarcosSenna
 */
public class ConfiguracoesFerramentaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfiguracoesFerramenta
     */
    public ConfiguracoesFerramentaJPanel() {
        initComponents();
        preencherCaminhoPoliticaOrganizacional();
        preencherCaminhoPlanoRisco(idProjetoSelecionado);
    }
    
    PoliticaOrganizacionalFacade politicaOrgFacade = new PoliticaOrganizacionalFacade();
    private int idProjetoSelecionado = 1;
    private List<Projeto> listaProjetos;
    ProjetoPlanoRiscoFacade projetoPlanoRiscoFacade = new ProjetoPlanoRiscoFacade();
    
    public void setProjetoSelecionado(int id){
        idProjetoSelecionado = id;
    }
    
    public void getListaProjetos(){
        listaProjetos = projetoPlanoRiscoFacade.getProjetos();
    }
    
    public void preencherCaminhoPoliticaOrganizacional(){
        try{
            Politicaorganizacional politicaOrg = new Politicaorganizacional();
            politicaOrg = politicaOrgFacade.getPolitica();
            caminhoPoliticaOrganizacionalJTextField.setText(politicaOrg.getCaminhoArquivo());
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    public void preencherCaminhoPlanoRisco(int idProjetoSelecionado) {

        if (idProjetoSelecionado == 0) {
            caminhoPlanoRiscoJTextField.setText("Nenhum projeto selecionado.");
        } else {
            try {
                Projeto projeto = new Projeto();
                projeto = projetoPlanoRiscoFacade.getProjetoWhereId(idProjetoSelecionado);
                if (projeto.getCaminhoPlanoDeRisco() == null) {
                    caminhoPlanoRiscoJTextField.setText("Nenhum diretório padrão de importação para o projeto selecionado.");
                } else {
                    caminhoPlanoRiscoJTextField.setText(projeto.getCaminhoPlanoDeRisco());
                }
            } catch (NullPointerException e) {

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        caminhoPoliticaOrganizacionalJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        caminhoPlanoRiscoJTextField = new javax.swing.JTextField();
        selecionarDiretorioPoliticaOrganizacionalJButton = new javax.swing.JButton();
        selecionarDiretorioPlanoRiscoJButton = new javax.swing.JButton();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jLabel1.setText("Configurações da Ferramenta:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Importação de Arquivos"));

        jLabel2.setText("Política Organizacional - Diretório de Importação: ");

        caminhoPoliticaOrganizacionalJTextField.setEditable(false);

        jLabel3.setText("Plano de Risco - Diretório de Importação:");

        caminhoPlanoRiscoJTextField.setEditable(false);

        selecionarDiretorioPoliticaOrganizacionalJButton.setText("Selecionar Diretório");
        selecionarDiretorioPoliticaOrganizacionalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarDiretorioPoliticaOrganizacionalJButtonActionPerformed(evt);
            }
        });

        selecionarDiretorioPlanoRiscoJButton.setText("Selecionar Diretório");
        selecionarDiretorioPlanoRiscoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarDiretorioPlanoRiscoJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caminhoPoliticaOrganizacionalJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(caminhoPlanoRiscoJTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecionarDiretorioPoliticaOrganizacionalJButton)
                    .addComponent(selecionarDiretorioPlanoRiscoJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(caminhoPoliticaOrganizacionalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selecionarDiretorioPoliticaOrganizacionalJButton))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(caminhoPlanoRiscoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionarDiretorioPlanoRiscoJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarDiretorioPoliticaOrganizacionalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarDiretorioPoliticaOrganizacionalJButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int retorno = fileChooser.showOpenDialog(null);
        
        if (retorno == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String path; 
            
            path = (file.getAbsolutePath()).toString();
            
            
            try{
                Politicaorganizacional politicaOrg = new Politicaorganizacional();
                politicaOrg = politicaOrgFacade.getPolitica();

                politicaOrg.setCaminhoArquivo(path);
                try {
                    politicaOrgFacade.setPolitica(politicaOrg);
                } catch (Exception ex) {
                    Logger.getLogger(OrganizacionalPoliticaOrganizacionalJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }

                JOptionPane.showMessageDialog(null, "Caminho configurado com sucesso.");
                preencherCaminhoPoliticaOrganizacional();
            }catch(Exception e){
                System.err.printf("Erro na configuração do caminho: %s. \n", e.getMessage());
            }
        }
    }//GEN-LAST:event_selecionarDiretorioPoliticaOrganizacionalJButtonActionPerformed

    private void selecionarDiretorioPlanoRiscoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarDiretorioPlanoRiscoJButtonActionPerformed
        if (idProjetoSelecionado == 0) {
            JOptionPane.showMessageDialog(this, "Não há projeto selecionado.");
        } else {
            Projeto projeto = new Projeto();
            projeto = projetoPlanoRiscoFacade.getProjetoWhereId(idProjetoSelecionado);

            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

            if (projeto.getCaminhoPlanoDeRisco() != null) {
                File arquivo = new File(projeto.getCaminhoPlanoDeRisco());
                fileChooser.setCurrentDirectory(arquivo);
            }

            int retorno = fileChooser.showOpenDialog(null);

            if (retorno == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                String path;

                path = (file.getAbsolutePath()).toString();

                try {
                    projeto.setCaminhoPlanoDeRisco(path);
                    try {
                        projetoPlanoRiscoFacade.alterarPlanoRisco(projeto);
                    } catch (Exception ex) {
                        Logger.getLogger(OrganizacionalPoliticaOrganizacionalJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    JOptionPane.showMessageDialog(null, "Caminho padrão configurado com sucesso.");
                    preencherCaminhoPlanoRisco(idProjetoSelecionado);
                } catch (Exception e) {
                    System.err.printf("Erro na configuração do caminho: %s. \n", e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_selecionarDiretorioPlanoRiscoJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caminhoPlanoRiscoJTextField;
    private javax.swing.JTextField caminhoPoliticaOrganizacionalJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton selecionarDiretorioPlanoRiscoJButton;
    private javax.swing.JButton selecionarDiretorioPoliticaOrganizacionalJButton;
    // End of variables declaration//GEN-END:variables
}
