/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.text.DateFormat;
import java.util.List;
import model.Planocontingencia;
import model.Planomitigacao;

/**
 *
 * @author Diogo
 */
public class MonitorarPlanosPendentesMaisInformaçõesInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MonitoracaoTarefasPlanosPendentesJInternalFrame
     */
    List<Planomitigacao> listaPlanoMitigacaoAtualizar;
    List<Planocontingencia> listaPlanoContingenciaAtualizar;
    private int idPlanoAtualizaMitigacao;
    private int idPlanoAtualizaContingencia;
    
    public MonitorarPlanosPendentesMaisInformaçõesInternalFrame() {
        initComponents();
        
    }  
    
    
    
    void preencheTelaParaPlanoDeMitigacao(List<Planomitigacao> listaPlaMitigacao, int idPlano) {
        DateFormat dataFormatada = DateFormat.getDateInstance(DateFormat.MEDIUM);
        String dataStr;
        
        identificacaoDoPlanoJTextField.setText(listaPlaMitigacao.get(idPlano).getIdentificacaoPlanoMitigacao());
        responsavelPeloPlanoJTextField.setText(listaPlaMitigacao.get(idPlano).getResponsavel());
        if(listaPlaMitigacao.get(idPlano).getIdMarcoDoProjeto() ==  null){
            dataStr = dataFormatada.format(listaPlaMitigacao.get(idPlano).getIdPontoDeControle().getDataPontoControle());
            dataLimiteJTextField.setText(dataStr);
        }
        else if(listaPlaMitigacao.get(idPlano).getIdPontoDeControle() == null){
            dataStr = dataFormatada.format(listaPlaMitigacao.get(idPlano).getIdMarcoDoProjeto().getDataMarcoProjeto());
            dataLimiteJTextField.setText(dataStr);
        }
        descricaoJTextArea.setText(listaPlaMitigacao.get(idPlano).getDescricaoPlanoMitigacao());
        comoSeraFeitoJTextArea.setText(listaPlaMitigacao.get(idPlano).getComoRealizar());
        informacoesAdicionaisJTextArea.setText(listaPlaMitigacao.get(idPlano).getInformacoesAdicionais());
        
        listaPlanoMitigacaoAtualizar = listaPlaMitigacao;
        idPlanoAtualizaMitigacao = idPlano;
    }
        

    void preencheTelaParaPlanoDeContingencia(List<Planocontingencia> listaPlaContigencia, int idPlano) {
        DateFormat dataFormatada = DateFormat.getDateInstance(DateFormat.MEDIUM);
        String dataStr;
        
        identificacaoDoPlanoJTextField.setText(listaPlaContigencia.get(idPlano).getIdentificacaoPlanoContingencia());
        responsavelPeloPlanoJTextField.setText(listaPlaContigencia.get(idPlano).getResponsavel());
        if(listaPlaContigencia.get(idPlano).getIdMarcoDoProjeto() ==  null){
            dataStr = dataFormatada.format(listaPlaContigencia.get(idPlano).getIdPontoDeControle().getDataPontoControle());
            dataLimiteJTextField.setText(dataStr);
        }
        else if(listaPlaContigencia.get(idPlano).getIdPontoDeControle() == null){
            dataStr = dataFormatada.format(listaPlaContigencia.get(idPlano).getIdMarcoDoProjeto().getDataMarcoProjeto());
            dataLimiteJTextField.setText(dataStr);
        }
        descricaoJTextArea.setText(listaPlaContigencia.get(idPlano).getDescricaoPlanoContingencia());
        comoSeraFeitoJTextArea.setText(listaPlaContigencia.get(idPlano).getComoRealizar());
        informacoesAdicionaisJTextArea.setText(listaPlaContigencia.get(idPlano).getInformacoesAdicionais());
        
        listaPlanoContingenciaAtualizar = listaPlaContigencia;
        idPlanoAtualizaContingencia = idPlano;
    }
    
    public void atualizaInternalFrame (){
        preencheTelaParaPlanoDeContingencia(listaPlanoContingenciaAtualizar, idPlanoAtualizaContingencia);
        preencheTelaParaPlanoDeMitigacao(listaPlanoMitigacaoAtualizar, idPlanoAtualizaMitigacao);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identificacaoDoPlanoJLabel = new javax.swing.JLabel();
        identificacaoDoPlanoJTextField = new javax.swing.JTextField();
        responsavelPeloPlanoJLabel = new javax.swing.JLabel();
        responsavelPeloPlanoJTextField = new javax.swing.JTextField();
        DataLimiteJLabel = new javax.swing.JLabel();
        dataLimiteJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoJTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        comoSeraFeitoJTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        informacoesAdicionaisJTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        identificacaoDoPlanoJLabel.setText("Identificação do Plano");

        identificacaoDoPlanoJTextField.setEditable(false);

        responsavelPeloPlanoJLabel.setText("Responsavel");

        responsavelPeloPlanoJTextField.setEditable(false);

        DataLimiteJLabel.setText("Data Limite");

        dataLimiteJTextField.setEditable(false);

        descricaoJTextArea.setEditable(false);
        descricaoJTextArea.setColumns(20);
        descricaoJTextArea.setLineWrap(true);
        descricaoJTextArea.setRows(1);
        descricaoJTextArea.setWrapStyleWord(true);
        descricaoJTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        jScrollPane1.setViewportView(descricaoJTextArea);

        comoSeraFeitoJTextArea.setEditable(false);
        comoSeraFeitoJTextArea.setColumns(20);
        comoSeraFeitoJTextArea.setLineWrap(true);
        comoSeraFeitoJTextArea.setRows(1);
        comoSeraFeitoJTextArea.setWrapStyleWord(true);
        comoSeraFeitoJTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Como será feito"));
        jScrollPane2.setViewportView(comoSeraFeitoJTextArea);

        informacoesAdicionaisJTextArea.setEditable(false);
        informacoesAdicionaisJTextArea.setColumns(20);
        informacoesAdicionaisJTextArea.setLineWrap(true);
        informacoesAdicionaisJTextArea.setRows(1);
        informacoesAdicionaisJTextArea.setWrapStyleWord(true);
        informacoesAdicionaisJTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Adicionais"));
        jScrollPane3.setViewportView(informacoesAdicionaisJTextArea);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(identificacaoDoPlanoJLabel)
                                    .addComponent(responsavelPeloPlanoJLabel)
                                    .addComponent(DataLimiteJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(identificacaoDoPlanoJTextField)
                                    .addComponent(responsavelPeloPlanoJTextField)
                                    .addComponent(dataLimiteJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificacaoDoPlanoJLabel)
                    .addComponent(identificacaoDoPlanoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responsavelPeloPlanoJLabel)
                    .addComponent(responsavelPeloPlanoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataLimiteJLabel)
                    .addComponent(dataLimiteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        
        identificacaoDoPlanoJTextField.setText("");
        responsavelPeloPlanoJTextField.setText("");
        dataLimiteJTextField.setText("");
        descricaoJTextArea.setText("");
        comoSeraFeitoJTextArea.setText("");
        informacoesAdicionaisJTextArea.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataLimiteJLabel;
    private javax.swing.JTextArea comoSeraFeitoJTextArea;
    private javax.swing.JTextField dataLimiteJTextField;
    private javax.swing.JTextArea descricaoJTextArea;
    private javax.swing.JLabel identificacaoDoPlanoJLabel;
    private javax.swing.JTextField identificacaoDoPlanoJTextField;
    private javax.swing.JTextArea informacoesAdicionaisJTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel responsavelPeloPlanoJLabel;
    private javax.swing.JTextField responsavelPeloPlanoJTextField;
    // End of variables declaration//GEN-END:variables

}
