/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Victor
 */
public class MonitoracaoQuadroDeAvisosJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MonitoracaoQuadroDeAvisosJPanel
     */
    public MonitoracaoQuadroDeAvisosJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MonitoracaoQuadroDeAvisosJPanel = new javax.swing.JPanel();
        MonitoracaoQuadroDeAvisosJScrollPane = new javax.swing.JScrollPane();
        MonitoracaoQuadroDeAvisosJTable = new javax.swing.JTable();

        MonitoracaoQuadroDeAvisosJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quadro de Avisos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        MonitoracaoQuadroDeAvisosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Atividade", "Data", "Ações"
            }
        ));
        MonitoracaoQuadroDeAvisosJScrollPane.setViewportView(MonitoracaoQuadroDeAvisosJTable);

        javax.swing.GroupLayout MonitoracaoQuadroDeAvisosJPanelLayout = new javax.swing.GroupLayout(MonitoracaoQuadroDeAvisosJPanel);
        MonitoracaoQuadroDeAvisosJPanel.setLayout(MonitoracaoQuadroDeAvisosJPanelLayout);
        MonitoracaoQuadroDeAvisosJPanelLayout.setHorizontalGroup(
            MonitoracaoQuadroDeAvisosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MonitoracaoQuadroDeAvisosJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        MonitoracaoQuadroDeAvisosJPanelLayout.setVerticalGroup(
            MonitoracaoQuadroDeAvisosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonitoracaoQuadroDeAvisosJPanelLayout.createSequentialGroup()
                .addComponent(MonitoracaoQuadroDeAvisosJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonitoracaoQuadroDeAvisosJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonitoracaoQuadroDeAvisosJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MonitoracaoQuadroDeAvisosJPanel;
    private javax.swing.JScrollPane MonitoracaoQuadroDeAvisosJScrollPane;
    private javax.swing.JTable MonitoracaoQuadroDeAvisosJTable;
    // End of variables declaration//GEN-END:variables
}
