/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Victor
 */
public class MonitoracaoTarefasHistoricoDeTarefasJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MonitoracaoTarefasHistoricoDeTarefasJPanel
     */
    public MonitoracaoTarefasHistoricoDeTarefasJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MonitoracaoTarefasHistoricoDeTarefasJPanel = new javax.swing.JPanel();
        MonitoracaoTarefasHistoricoDeTarefasJScrollPane = new javax.swing.JScrollPane();
        MonitoracaoTarefasHistoricoDeTarefasJTable = new javax.swing.JTable();

        MonitoracaoTarefasHistoricoDeTarefasJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Histórico de Tarefas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        MonitoracaoTarefasHistoricoDeTarefasJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Checar ocorrência de riscos: Ponto 10", "25/05/2014"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarefas", "Realizado em:"
            }
        ));
        MonitoracaoTarefasHistoricoDeTarefasJScrollPane.setViewportView(MonitoracaoTarefasHistoricoDeTarefasJTable);

        javax.swing.GroupLayout MonitoracaoTarefasHistoricoDeTarefasJPanelLayout = new javax.swing.GroupLayout(MonitoracaoTarefasHistoricoDeTarefasJPanel);
        MonitoracaoTarefasHistoricoDeTarefasJPanel.setLayout(MonitoracaoTarefasHistoricoDeTarefasJPanelLayout);
        MonitoracaoTarefasHistoricoDeTarefasJPanelLayout.setHorizontalGroup(
            MonitoracaoTarefasHistoricoDeTarefasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MonitoracaoTarefasHistoricoDeTarefasJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        MonitoracaoTarefasHistoricoDeTarefasJPanelLayout.setVerticalGroup(
            MonitoracaoTarefasHistoricoDeTarefasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonitoracaoTarefasHistoricoDeTarefasJPanelLayout.createSequentialGroup()
                .addComponent(MonitoracaoTarefasHistoricoDeTarefasJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonitoracaoTarefasHistoricoDeTarefasJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonitoracaoTarefasHistoricoDeTarefasJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MonitoracaoTarefasHistoricoDeTarefasJPanel;
    private javax.swing.JScrollPane MonitoracaoTarefasHistoricoDeTarefasJScrollPane;
    private javax.swing.JTable MonitoracaoTarefasHistoricoDeTarefasJTable;
    // End of variables declaration//GEN-END:variables
}
