/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import facade.OrganizacaoDetalhesFacade;
import javax.swing.JOptionPane;
import model.Organizacao;
import model.Politicaorganizacional;

/**
 *
 * @author Diego
 */
public class OrganizacionalDetalhesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Organizacional_Detalhes
     */
    OrganizacaoDetalhesFacade organizacaoDetalhesFacade = new OrganizacaoDetalhesFacade();
    
    public OrganizacionalDetalhesJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        empresaJLabel = new javax.swing.JLabel();
        cnpjJLabel = new javax.swing.JLabel();
        enderecoJLabel = new javax.swing.JLabel();
        salvarAlteracoesJButton = new javax.swing.JButton();
        empresaJTextField = new javax.swing.JTextField();
        cnpjJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        enderecoJTextArea = new javax.swing.JTextArea();

        JPanel1.setPreferredSize(new java.awt.Dimension(860, 508));

        empresaJLabel.setText("Empresa:");

        cnpjJLabel.setText("CNPJ:");

        enderecoJLabel.setText("Endereço:");

        salvarAlteracoesJButton.setText("Salvar Alterações");
        salvarAlteracoesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAlteracoesJButtonActionPerformed(evt);
            }
        });

        enderecoJTextArea.setColumns(20);
        enderecoJTextArea.setLineWrap(true);
        enderecoJTextArea.setRows(5);
        enderecoJTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(enderecoJTextArea);

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel1Layout.createSequentialGroup()
                        .addComponent(empresaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empresaJTextField))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvarAlteracoesJButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel1Layout.createSequentialGroup()
                        .addComponent(enderecoJLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel1Layout.createSequentialGroup()
                        .addComponent(cnpjJLabel)
                        .addGap(20, 20, 20)
                        .addComponent(cnpjJTextField)))
                .addContainerGap())
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empresaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enderecoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salvarAlteracoesJButton)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarAlteracoesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAlteracoesJButtonActionPerformed
        Organizacao org1 = organizacaoDetalhesFacade.getDetalhes();
        org1.setNomeOrganizacao(empresaJTextField.getText());
        org1.setCnpj(Integer.parseInt(cnpjJTextField.getText()));
        org1.setEndereco(enderecoJTextArea.getText());
        organizacaoDetalhesFacade.alterarDetalhes(org1);
        repaint();
        JOptionPane.showMessageDialog(this, "Dados alterados com sucesso.");
    }//GEN-LAST:event_salvarAlteracoesJButtonActionPerformed

    public void preencheForm() {
        Organizacao org = organizacaoDetalhesFacade.getDetalhes();
        empresaJTextField.setText(org.getNomeOrganizacao());
        cnpjJTextField.setText(Integer.toString( (int) org.getCnpj()));
        enderecoJTextArea.setText(org.getEndereco());
        
        System.out.println(org.getNomeOrganizacao()+"\n");
        org = null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JLabel cnpjJLabel;
    private javax.swing.JTextField cnpjJTextField;
    private javax.swing.JLabel empresaJLabel;
    private javax.swing.JTextField empresaJTextField;
    private javax.swing.JLabel enderecoJLabel;
    private javax.swing.JTextArea enderecoJTextArea;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton salvarAlteracoesJButton;
    // End of variables declaration//GEN-END:variables
}
