/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.JFrame;

/**
 *
 * @author Victor
 */
public class RiscosPriorizarRiscosJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RiscosPriorizarRiscosJPanel
     */
    public RiscosPriorizarRiscosJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RiscosPriorizarRiscosJPanel = new javax.swing.JPanel();
        RiscosPriorizarRiscosJScrollPane = new javax.swing.JScrollPane();
        RiscosPriorizarRiscosJTable = new javax.swing.JTable();
        RiscosPriorizarRiscosSalvarAlteracoesJButton = new javax.swing.JButton();
        RiscosPriorizarRiscosSelecionarMonitorarJButton = new javax.swing.JButton();
        RiscosPriorizarRiscosAcoesJPanel = new javax.swing.JPanel();
        RiscosPriorizarRiscosAcoesAumentarPrioridadeJButton = new javax.swing.JButton();
        RiscosPriorizarRiscosAcoesDiminuirPrioridadeJButton = new javax.swing.JButton();
        RiscosPriorizarRiscosacoesDefinirManualJButton = new javax.swing.JButton();
        RiscosPriorizarRiscosAcoesJSpinner = new javax.swing.JSpinner();

        RiscosPriorizarRiscosJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Priorizar Riscos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        RiscosPriorizarRiscosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"R01", "20", "Alto", "15", "0", "Novo"},
                {"R02", "35", "Alto", "15", "0", "Novo"},
                {"R03", "80", "Alto", "60", "0", "Novo"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Identificação", "Probabilidade", "Impacto", "Grau de Severidade", "Prioridade", "Estado"
            }
        ));
        RiscosPriorizarRiscosJScrollPane.setViewportView(RiscosPriorizarRiscosJTable);

        RiscosPriorizarRiscosSalvarAlteracoesJButton.setText("Salvar alterações de risco");

        RiscosPriorizarRiscosSelecionarMonitorarJButton.setText("Selecionar riscos para monitorar");
        RiscosPriorizarRiscosSelecionarMonitorarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiscosPriorizarRiscosSelecionarMonitorarJButtonActionPerformed(evt);
            }
        });

        RiscosPriorizarRiscosAcoesJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        RiscosPriorizarRiscosAcoesAumentarPrioridadeJButton.setText("Aumentar prioridade");

        RiscosPriorizarRiscosAcoesDiminuirPrioridadeJButton.setText("Diminuir prioridade");

        RiscosPriorizarRiscosacoesDefinirManualJButton.setText("Definir prioridade manual");
        RiscosPriorizarRiscosacoesDefinirManualJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiscosPriorizarRiscosacoesDefinirManualJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RiscosPriorizarRiscosAcoesJPanelLayout = new javax.swing.GroupLayout(RiscosPriorizarRiscosAcoesJPanel);
        RiscosPriorizarRiscosAcoesJPanel.setLayout(RiscosPriorizarRiscosAcoesJPanelLayout);
        RiscosPriorizarRiscosAcoesJPanelLayout.setHorizontalGroup(
            RiscosPriorizarRiscosAcoesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RiscosPriorizarRiscosAcoesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RiscosPriorizarRiscosAcoesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RiscosPriorizarRiscosAcoesJPanelLayout.createSequentialGroup()
                        .addComponent(RiscosPriorizarRiscosacoesDefinirManualJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(RiscosPriorizarRiscosAcoesJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RiscosPriorizarRiscosAcoesJPanelLayout.createSequentialGroup()
                        .addGroup(RiscosPriorizarRiscosAcoesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RiscosPriorizarRiscosAcoesAumentarPrioridadeJButton)
                            .addComponent(RiscosPriorizarRiscosAcoesDiminuirPrioridadeJButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        RiscosPriorizarRiscosAcoesJPanelLayout.setVerticalGroup(
            RiscosPriorizarRiscosAcoesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RiscosPriorizarRiscosAcoesJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RiscosPriorizarRiscosAcoesAumentarPrioridadeJButton)
                .addGap(18, 18, 18)
                .addComponent(RiscosPriorizarRiscosAcoesDiminuirPrioridadeJButton)
                .addGap(18, 18, 18)
                .addGroup(RiscosPriorizarRiscosAcoesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RiscosPriorizarRiscosacoesDefinirManualJButton)
                    .addComponent(RiscosPriorizarRiscosAcoesJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout RiscosPriorizarRiscosJPanelLayout = new javax.swing.GroupLayout(RiscosPriorizarRiscosJPanel);
        RiscosPriorizarRiscosJPanel.setLayout(RiscosPriorizarRiscosJPanelLayout);
        RiscosPriorizarRiscosJPanelLayout.setHorizontalGroup(
            RiscosPriorizarRiscosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RiscosPriorizarRiscosJScrollPane)
            .addGroup(RiscosPriorizarRiscosJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RiscosPriorizarRiscosAcoesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RiscosPriorizarRiscosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RiscosPriorizarRiscosJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RiscosPriorizarRiscosSalvarAlteracoesJButton)
                        .addContainerGap())
                    .addGroup(RiscosPriorizarRiscosJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RiscosPriorizarRiscosSelecionarMonitorarJButton)
                        .addContainerGap(339, Short.MAX_VALUE))))
        );
        RiscosPriorizarRiscosJPanelLayout.setVerticalGroup(
            RiscosPriorizarRiscosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RiscosPriorizarRiscosJPanelLayout.createSequentialGroup()
                .addComponent(RiscosPriorizarRiscosJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(RiscosPriorizarRiscosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RiscosPriorizarRiscosAcoesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RiscosPriorizarRiscosJPanelLayout.createSequentialGroup()
                        .addComponent(RiscosPriorizarRiscosSelecionarMonitorarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RiscosPriorizarRiscosSalvarAlteracoesJButton)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RiscosPriorizarRiscosJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RiscosPriorizarRiscosJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RiscosPriorizarRiscosacoesDefinirManualJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiscosPriorizarRiscosacoesDefinirManualJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RiscosPriorizarRiscosacoesDefinirManualJButtonActionPerformed

    private void RiscosPriorizarRiscosSelecionarMonitorarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiscosPriorizarRiscosSelecionarMonitorarJButtonActionPerformed

        SelecionarRiscosParaMonitorarJFrame selecionar = new SelecionarRiscosParaMonitorarJFrame();
        selecionar.setLocationRelativeTo(this);
        selecionar.setVisible(true);
        selecionar.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
// TODO add your handling code here:
    }//GEN-LAST:event_RiscosPriorizarRiscosSelecionarMonitorarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RiscosPriorizarRiscosAcoesAumentarPrioridadeJButton;
    private javax.swing.JButton RiscosPriorizarRiscosAcoesDiminuirPrioridadeJButton;
    private javax.swing.JPanel RiscosPriorizarRiscosAcoesJPanel;
    private javax.swing.JSpinner RiscosPriorizarRiscosAcoesJSpinner;
    private javax.swing.JPanel RiscosPriorizarRiscosJPanel;
    private javax.swing.JScrollPane RiscosPriorizarRiscosJScrollPane;
    private javax.swing.JTable RiscosPriorizarRiscosJTable;
    private javax.swing.JButton RiscosPriorizarRiscosSalvarAlteracoesJButton;
    private javax.swing.JButton RiscosPriorizarRiscosSelecionarMonitorarJButton;
    private javax.swing.JButton RiscosPriorizarRiscosacoesDefinirManualJButton;
    // End of variables declaration//GEN-END:variables
}
