/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import facade.RiscosRiscosOcorridosFacade;
import facade.RiscosSelecionarRiscosParaMonitorarFacade;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Historicorisco;
import model.Projeto;

/**
 *
 * @author Victor
 */
public class RiscosRiscosOcorridosJPanel extends javax.swing.JPanel {

    RiscosRiscosOcorridosFacade riscosOcorridosFacade = new RiscosRiscosOcorridosFacade();
    // criando tabela
    private JTable tabelaRiscosOcorridos;
    private DefaultTableModel modeloTabelaRiscosOcorridos;
    
    private Projeto projetoSelecionado;
    
    private List<Historicorisco> listaHistoricoRisco;
    private Historicorisco historicoriscoSelecionado;
    
    /**
     * Creates new form RiscosRiscosOcorridosJPanel
     */
    public RiscosRiscosOcorridosJPanel() {
        initComponents();
    }

     public void getProjeto (Projeto projeto){
        this.projetoSelecionado = projeto;
    }
    
    public void criarTabelaRiscosOcorridos(){
        
        tabelaRiscosOcorridos = new JTable();
        modeloTabelaRiscosOcorridos = new DefaultTableModel();
        modeloTabelaRiscosOcorridos.setColumnIdentifiers(new Object[] {"Identificação", "Descrição", "Data de ocorrencia"});
        tabelaRiscosOcorridos.setModel(modeloTabelaRiscosOcorridos);
        tabelaRiscosOcorridosJScrollPane.setViewportView(tabelaRiscosOcorridos);
        
        definirEventosTabelaRiscosOcorridos();
    }
    
    public void popularTabelaRiscosOcorridos(){
        
        listaHistoricoRisco = riscosOcorridosFacade.getListaHistoricoriscosByIdProjeto(projetoSelecionado.getIdProjeto());
        for (int i=0; i < listaHistoricoRisco.size(); i++){
            
            DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);
            Date data = listaHistoricoRisco.get(i).getDataOcorrencia();
               
            
            Object[] linha = new Object[]{listaHistoricoRisco.get(i).getIdRisco().getIdentificacao(), listaHistoricoRisco.get(i).getIdRisco().getDescricao(), df.format(data)};
            modeloTabelaRiscosOcorridos.addRow(linha);
            
            //System.err.println("subcondição: ---" + listaHistoricoRisco.get(i).getSubcondicaoList().get(i));
        }
    }
    
    public void definirEventosTabelaRiscosOcorridos() {
        tabelaRiscosOcorridos.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    int selected = tabelaRiscosOcorridos.getSelectedRow();
                    for (int i = 0; i < listaHistoricoRisco.size(); i++) {
                        if (tabelaRiscosOcorridos.getValueAt(tabelaRiscosOcorridos.getSelectedRow(), 0).equals(listaHistoricoRisco.get(i).getIdRisco().getIdentificacao())) {
                            historicoriscoSelecionado = listaHistoricoRisco.get(i);
                            System.err.println("----------->" + listaHistoricoRisco.get(i).getIdHistoricoRisco());
                            break;
                        }
                    }
                } else if (e.getClickCount() == 2) {
                    int selected = tabelaRiscosOcorridos.getSelectedRow();
                    for (int i = 0; i < listaHistoricoRisco.size(); i++) {
                        if (tabelaRiscosOcorridos.getValueAt(tabelaRiscosOcorridos.getSelectedRow(), 0).equals(listaHistoricoRisco.get(i).getIdRisco().getIdentificacao())) {

                            historicoriscoSelecionado = listaHistoricoRisco.get(i);
                            System.err.println("----------->" + listaHistoricoRisco.get(i).getIdHistoricoRisco());
                            PrincipalJFrame.riscosRiscosOcorridosJInternalFrame.preencherTela(historicoriscoSelecionado);
                            PrincipalJFrame.aparecerInternalFrameRiscosOcorridos();
                            break;
                        }
                    }
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RiscosRiscosOcorridosJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tabelaRiscosOcorridosJScrollPane = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        RiscosRiscosOcorridosJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Riscos Ocorridos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("* Duplo clique para mais informações");

        javax.swing.GroupLayout RiscosRiscosOcorridosJPanelLayout = new javax.swing.GroupLayout(RiscosRiscosOcorridosJPanel);
        RiscosRiscosOcorridosJPanel.setLayout(RiscosRiscosOcorridosJPanelLayout);
        RiscosRiscosOcorridosJPanelLayout.setHorizontalGroup(
            RiscosRiscosOcorridosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RiscosRiscosOcorridosJPanelLayout.createSequentialGroup()
                .addComponent(tabelaRiscosOcorridosJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RiscosRiscosOcorridosJPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RiscosRiscosOcorridosJPanelLayout.setVerticalGroup(
            RiscosRiscosOcorridosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RiscosRiscosOcorridosJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RiscosRiscosOcorridosJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabelaRiscosOcorridosJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RiscosRiscosOcorridosJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RiscosRiscosOcorridosJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RiscosRiscosOcorridosJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane tabelaRiscosOcorridosJScrollPane;
    // End of variables declaration//GEN-END:variables
}
